"""Add M-Pesa transaction fields to payment model

Revision ID: 2e3608ae0691
Revises: 502927a9bdd5
Create Date: 2025-11-02 19:15:40.038143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3608ae0691'
down_revision = '502927a9bdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
