"""Add regenerated_count and last_downloaded to certificate

Revision ID: 3fc7948898db
Revises: 83c99239d7f9
Create Date: 2025-11-03 12:04:50.962075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc7948898db'
down_revision = '83c99239d7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regenerated_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_downloaded', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('last_downloaded')
        batch_op.drop_column('regenerated_count')

    # ### end Alembic commands ###
