"""Add anti-cheat fields to ModuleProgress

Revision ID: 502927a9bdd5
Revises: eedaf88dc1c8
Create Date: 2025-11-02 01:16:39.991469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502927a9bdd5'
down_revision = 'eedaf88dc1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reading_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interactive_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anti_cheat_flags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.drop_column('anti_cheat_flags')
        batch_op.drop_column('time_verified')
        batch_op.drop_column('interactive_completed')
        batch_op.drop_column('reading_completed')
        batch_op.drop_column('quiz_completed')

    # ### end Alembic commands ###
