"""Add response fields to teacher request

Revision ID: 83c99239d7f9
Revises: ef7f61870553
Create Date: 2025-11-03 04:31:30.410203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c99239d7f9'
down_revision = 'ef7f61870553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_responded', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_request', schema=None) as batch_op:
        batch_op.drop_column('date_responded')
        batch_op.drop_column('response_message')

    # ### end Alembic commands ###
