"""Add ModuleProgress model and update Enrollment progress calculation

Revision ID: eedaf88dc1c8
Revises: fffb5b591d4e
Create Date: 2025-11-01 23:49:13.328734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedaf88dc1c8'
down_revision = 'fffb5b591d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
