"""Add course_id and is_final_quiz to Quiz model

Revision ID: ef7f61870553
Revises: 2e3608ae0691
Create Date: 2025-11-02 22:30:14.907792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7f61870553'
down_revision = '2e3608ae0691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_final_quiz', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_course_id', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_final_quiz')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
