"""Add skill payment support

Revision ID: fabf2d2defe9
Revises: 
Create Date: 2025-10-31 02:07:36.147524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabf2d2defe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_payment_skill_id', 'skill', ['skill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_skill_id', type_='foreignkey')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('skill_id')

    # ### end Alembic commands ###
